# automatically generated by the FlatBuffers compiler, do not modify

# namespace: OctreeData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OctreeNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OctreeNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOctreeNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OctreeNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OctreeNode
    def PosX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OctreeNode
    def PosY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OctreeNode
    def PosZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OctreeNode
    def Level(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OctreeNode
    def Octant(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OctreeNode
    def Occupancy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OctreeNode
    def ParentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OctreeNode
    def ParentOccupancy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OctreeNode
    def NeighborOccupancies(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # OctreeNode
    def NeighborOccupanciesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # OctreeNode
    def NeighborOccupanciesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OctreeNode
    def NeighborOccupanciesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

def OctreeNodeStart(builder): builder.StartObject(9)
def Start(builder):
    return OctreeNodeStart(builder)
def OctreeNodeAddPosX(builder, posX): builder.PrependInt32Slot(0, posX, 0)
def AddPosX(builder, posX):
    return OctreeNodeAddPosX(builder, posX)
def OctreeNodeAddPosY(builder, posY): builder.PrependInt32Slot(1, posY, 0)
def AddPosY(builder, posY):
    return OctreeNodeAddPosY(builder, posY)
def OctreeNodeAddPosZ(builder, posZ): builder.PrependInt32Slot(2, posZ, 0)
def AddPosZ(builder, posZ):
    return OctreeNodeAddPosZ(builder, posZ)
def OctreeNodeAddLevel(builder, level): builder.PrependInt32Slot(3, level, 0)
def AddLevel(builder, level):
    return OctreeNodeAddLevel(builder, level)
def OctreeNodeAddOctant(builder, octant): builder.PrependInt32Slot(4, octant, 0)
def AddOctant(builder, octant):
    return OctreeNodeAddOctant(builder, octant)
def OctreeNodeAddOccupancy(builder, occupancy): builder.PrependInt32Slot(5, occupancy, 0)
def AddOccupancy(builder, occupancy):
    return OctreeNodeAddOccupancy(builder, occupancy)
def OctreeNodeAddParentId(builder, parentId): builder.PrependInt32Slot(6, parentId, 0)
def AddParentId(builder, parentId):
    return OctreeNodeAddParentId(builder, parentId)
def OctreeNodeAddParentOccupancy(builder, parentOccupancy): builder.PrependInt32Slot(7, parentOccupancy, 0)
def AddParentOccupancy(builder, parentOccupancy):
    return OctreeNodeAddParentOccupancy(builder, parentOccupancy)
def OctreeNodeAddNeighborOccupancies(builder, neighborOccupancies): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(neighborOccupancies), 0)
def AddNeighborOccupancies(builder, neighborOccupancies):
    return OctreeNodeAddNeighborOccupancies(builder, neighborOccupancies)
def OctreeNodeStartNeighborOccupanciesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartNeighborOccupanciesVector(builder, numElems):
    return OctreeNodeStartNeighborOccupanciesVector(builder, numElems)
def OctreeNodeEnd(builder): return builder.EndObject()
def End(builder):
    return OctreeNodeEnd(builder)